name: Bump Homebrew Casks
on:
  schedule:
    # Runs at 2 AM EST±DST every day
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  bump-homebrew-casks:
    runs-on: macos-latest
    steps:
      - uses: kitschpatrol/github-action-homebrew-bump-cask@v3
        with:
          tap: kitschpatrol/tap # Bump all outdated casks in this tap
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}} # Required, custom GitHub access token with only the 'public_repo' scope enabled
          livecheck: true # Need to set this input if want to use `brew livecheck`
