name: Bump Homebrew Casks
on:
  schedule:
    # Runs at 2 AM EST±DST every day
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew casks
        uses: eugenesvk/action-homebrew-bump-cask@3.8.4
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          tap: kitschpatrol/stuff
          livecheck: true
